Increment17
AnnV0lokitina/short-url-service pull request #16
Opened 2022-05-31 23:09 UTC by AnnV0lokitina

2022-06-05 18:55 UTC, Barugoo commented on cmd/shortener/main.go
> +	_ "net/http/pprof"
Запрос на `localhost:8080/debug/pprof` мне возвращает 404
Проблема в том, что импорт пакета `net/http/pprof` регистрирует хэндлеры профилировщика на `http.DefaultServer`, а не на тот сервер, который ты инициализируешь в пакете `handlers`. Если бы мы запускали сервер приложения через `http.ListenAndServe` то у нас бы внутри запускался `http.DefaultServer` и импорта `_ "net/http/pprof"` было бы достаточно. Но в нашем случае, как мы и обсуждали на 1-1, нам необходимо ручками регистрировать хэндлеры профилировщика:
```go
// объявление эндпоинтов...
h.Delete("/api/user/urls", h.DeleteBatch())

// хэндлеры профилировщика
h.Get("/debug/pprof", pprof.Index)
h.Get("/debug/pprof/profile", pprof.Profile)

```

2022-06-05 20:34 UTC, Barugoo commented on cmd/shortener/main.go
> +	_ "net/http/pprof"
UPD: увидел, шо ты стартанула сервер отдельный на 6060 порту, пардон

2022-06-05 21:29 UTC, Barugoo commented on cmd/shortener/main.go
> +	_ "net/http/pprof"
Касаемо того, что мы с тобой на 1-1 не видели ничего в профилях - так как мы работали с хранилкой в памяти и делали запросы вручную, нагрузка на CPU была настолько ничтожной, что pprof ничего не смог собрать. 

На боевом окружении, обычно с недостатком нагрузки на сервере для получения профиля проблем нет, однако нам для сбора профилей с ручки `/debug/pprof` потребуется эту самую нагрузку сымитировать. 

Для этого отлично подойдет утилита `ab` (apache bench), здесь я выполняю 100000 запросов в два потока на получение списка урлов для юзера, куку которого я передал параметром:
```bash
 ab -C login=2d48528e61686cee43afa7e43266705b0007f6e9553d4299c8e7ba8bdf7583cd66595753 -n 100000 -c 2 http://127.0.0.1:8080/api/user/urls
```

Как итог, pprof выдал такую штуку:
```bash
(pprof) top20
Showing nodes accounting for 2.17s, 94.76% of 2.29s total
Dropped 56 nodes (cum <= 0.01s)
Showing top 20 nodes out of 126
      flat  flat%   sum%        cum   cum%
     0.88s 38.43% 38.43%      0.95s 41.48%  syscall.syscall
     0.33s 14.41% 52.84%      0.34s 14.85%  runtime.pthread_cond_signal
     0.23s 10.04% 62.88%      0.23s 10.04%  runtime.libcCall
     0.22s  9.61% 72.49%      0.26s 11.35%  runtime.kevent
     0.22s  9.61% 82.10%      0.28s 12.23%  runtime.pthread_cond_wait
     0.07s  3.06% 85.15%      0.12s  5.24%  runtime.usleep
     0.06s  2.62% 87.77%      0.06s  2.62%  syscall.syscall6
     0.03s  1.31% 89.08%      0.03s  1.31%  runtime.madvise
     0.03s  1.31% 90.39%      0.03s  1.31%  runtime.nanotime1
     0.01s  0.44% 90.83%      0.04s  1.75%  crypto/sha256.(*digest).Sum
     0.01s  0.44% 91.27%      0.02s  0.87%  github.com/AnnV0lokitina/short-url-service.git/internal/sqlrepo.(*Repo).GetUserURLList
     0.01s  0.44% 91.70%      0.02s  0.87%  net/http.(*chunkWriter).writeHeader
     0.01s  0.44% 92.14%      0.54s 23.58%  net/http.(*response).finishRequest
     0.01s  0.44% 92.58%      0.11s  4.80%  net/textproto.(*Reader).readLineSlice
     0.01s  0.44% 93.01%      0.06s  2.62%  runtime.copystack
     0.01s  0.44% 93.45%      0.05s  2.18%  runtime.gentraceback
     0.01s  0.44% 93.89%      0.02s  0.87%  runtime.pcdatavalue
     0.01s  0.44% 94.32%      0.03s  1.31%  runtime.pcvalue
     0.01s  0.44% 94.76%      0.02s  0.87%  runtime.step
         0     0% 94.76%      0.10s  4.37%  bufio.(*Reader).ReadLine

2022-06-05 21:30 UTC, Barugoo commented on cmd/shortener/main.go
> +	_ "net/http/pprof"
Короче говоря, pprof который ты запустила на порту 6060 работает, все ОК

2022-06-05 21:51 UTC, Barugoo commented on cmd/shortener/main.go
> +	handlerPkg "github.com/AnnV0lokitina/short-url-service.git/internal/handler"
Название модуля в `go.mod` судя по всему заканчивается `.git`
Нужно убрать `.git`, иначе будет работать некорректно с некоторыми утилитами

2022-06-05 21:51 UTC, Barugoo commented on internal/entity/batch_url.go
> +// BatchURLItem Information about URL batch.
Я бы написал:
```go
// BatchURLItem contains info about URL batch
```

2022-06-05 21:52 UTC, Barugoo commented on internal/entity/batch_url.go
> +	URL           *URL   // url list
Почему `url list`, но при этом это не коллекция, а указатель на урл в единственном экземпляре?

2022-06-05 21:53 UTC, Barugoo commented on internal/entity/batch_url.go
> +	CorrelationID string // correlation id
->
```go
// CorrelationID is used to ...

2022-06-05 21:53 UTC, Barugoo commented on internal/entity/batch_url.go
> +// NewBatchURLItem Create new BatchURLItem.
```go
// NewBatchURLItem creates new BatchURLItem

2022-06-05 21:54 UTC, Barugoo commented on internal/entity/record.go
> +	UserID      uint32 `json:"user_id"`      // user, who save url
```go
// owner's user ID

2022-06-05 21:54 UTC, Barugoo commented on internal/entity/record.go
> +	OriginalURL string `json:"original_url"` // original url
Кажется, что эти комментарии излишни

2022-06-05 21:56 UTC, Barugoo commented on internal/handler/handler.go
> +// Service declare interface if services
```go
Service interface describes business-logic layer

2022-06-05 21:57 UTC, Barugoo commented on internal/handler/handler.go
> +// Handler keep information to handle requests.
```go
// Handler structure holds dependencies for server handlers

2022-06-05 21:57 UTC, Barugoo commented on internal/handler/ping_db.go
> +// PingDB Check if db is available.
*checks

2022-06-05 21:58 UTC, Barugoo commented on internal/handler/set_batch_url.go
> +// ShortenBatch Set URL batch to shorten in json format.
```go
// ShortenBatch handler is used to process batches of urls

2022-06-05 22:05 UTC, Barugoo commented on internal/handler/set_batch_url_test.go
> +}
Круто, что ты добавила в example тесты, но этот функционал больше нужен для юнит-тестов, а не для интеграционных. Здесь по заданию ожидается что-то вроде 
https://medium.com/@danielphan/try-things-testing-part-1-a734215b25fa

![изображение](https://user-images.githubusercontent.com/27661724/172072548-9f5f6b7c-8389-4f84-a84d-71563cacc0dd.png)

2022-06-05 22:14 UTC, Barugoo commented on internal/repo/repo_bench_test.go
> +func BenchmarkRepo_GetURL(b *testing.B) {
Бенчмарки предназначены для тестирования производительности CPU-bound задач, которые включают: математические вычисления (например хэширование), операции над коллекциями (поиск, вставка, удаление и тд). В нашем случае можно сделать две реализации хранилки урлов - через массив/линкед-лист и через мапку и сравнить их производительность в бенчмарках на разных операциях.

2022-06-05 22:14 UTC, Barugoo requested changes
Есть замечания

2022-06-13 12:25 UTC, rktkov requested changes

2022-06-13 12:25 UTC, rktkov commented on internal/handler/io_scheme.go
>  // JSONListToURLList конвертация полученых данных объекты приложения
Комментарии стоит перевести на английский, чтобы они были совпадали с остальными по языку.

2022-06-13 12:25 UTC, rktkov commented on internal/handler/handler.go
> +// Service declare interface if services
Стоит учесть предложения из прошлых комментариев, здесь и дальше по коду.

2022-06-15 13:43 UTC, rktkov approved these changes

2022-06-15 13:43 UTC, rktkov commented on cmd/shortener/main.go
> +	go func() {
Зачем запускать этот сервер?

2022-06-15 13:43 UTC, rktkov commented on internal/repo/bench.result
> +goos: linux
Нам нужны результаты в репозитории?

2022-06-15 13:43 UTC, rktkov commented on internal/repo_array/bench.result
> +goos: linux
См. вопрос выше.

2022-07-05 22:58 UTC, merged